spark_master:
    image: xiocode/spark-master
    environment:
        - SPARK_MASTER_SERVICE_HOST=0.0.0.0
    ports:
        - "8080:8080"
        - "7077:7077"

spark_worker_1:
    image: xiocode/spark-worker
    environment:
        - SPARK_MASTER_SERVICE_HOST=0.0.0.0
    ports:
        - "8081:8081"
    links:
        - "spark_master:spark-master"

spark_worker_2:
    image: xiocode/spark-worker
    environment:
        - SPARK_MASTER_SERVICE_HOST=0.0.0.0
    ports:
        - "8081:8081"
    links:
        - "spark_master:spark-master"
